# Generated by Django 3.0.3 on 2020-03-04 10:04

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_auto_20200304_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listeningquestion',
            name='answer_choices',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=150), null=True, size=None),
        ),
    ]
