# Generated by Django 3.0.3 on 2020-03-21 17:25

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0006_auto_20200321_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listeningquestion',
            name='answer_choices',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=150), default=list, size=None),
        ),
    ]
