# Generated by Django 3.0.3 on 2020-03-22 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0008_auto_20200321_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='readingquestion',
            name='correct_choice_index',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=1, null=True),
        ),
        migrations.AddField(
            model_name='readingquestion',
            name='description',
            field=models.CharField(blank=True, max_length=180),
        ),
    ]
