# Generated by Django 3.0.3 on 2020-03-22 07:00

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0009_auto_20200322_0658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readingquestion',
            name='question_texts',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=220), blank=True, default=list, null=True, size=None),
        ),
    ]
