# Generated by Django 3.0.3 on 2020-03-22 15:32

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0010_auto_20200322_0700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readingquestion',
            name='answer_image_paths',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=220), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='readingquestion',
            name='correct_answers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.BooleanField(), blank=True, default=list, size=None),
        ),
    ]
