# Generated by Django 3.0.3 on 2020-04-18 06:23

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0011_auto_20200322_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='image_path',
            field=models.CharField(max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='form',
            name='text',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='listeningquestion',
            name='audio_path',
            field=models.CharField(max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='listeningquestion',
            name='question_text',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='readingquestion',
            name='image_path',
            field=models.CharField(blank=True, max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='readingquestion',
            name='question_text',
            field=models.TextField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='readingquestion',
            name='question_texts',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=220), blank=True, default=list, null=True, size=None, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='word',
            unique_together={('theme', 'value')},
        ),
    ]
