# Generated by Django 3.0.3 on 2020-04-18 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0012_auto_20200418_0623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='listeningquestion',
            name='audio_path',
            field=models.CharField(max_length=120),
        ),
    ]
