# Generated by Django 3.0.3 on 2020-04-18 07:31

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0014_auto_20200418_0728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readingquestion',
            name='question_text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='readingquestion',
            name='question_texts',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=220), blank=True, default=list, null=True, size=None),
        ),
        migrations.AlterUniqueTogether(
            name='readingquestion',
            unique_together={('question_text', 'question_texts')},
        ),
    ]
