# Generated by Django 3.0.3 on 2020-04-21 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0016_auto_20200421_1100'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='aliasName',
            new_name='alias_name',
        ),
    ]
